title: Zhan Cheng Homepage
page-top-title: Zhan Cheng Homepage
top-section-bg-text: A Casual Math Fan Dreaming of AI World
home-subtitle: Zhan Cheng
copyright-text: '&copy; Jerry Yin 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
